#============================================================================
# init.vim --- My SpaceVim config
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
#=============================================================================

# SpaceVim options {{{
[options]
    default_indent = 4
    enable_debug = 1
    enable_ale = 0
    filemanager = "defx"
    filetree_direction = "right"
    # enable_ycm = 1
    # snippet_engine = "ultisnips"
    line_on_the_fly = 0
    # default_custom_leader = "e"
    enable_statusline_mode = true
    # enable_ale = false
    # enable_neomake = false
    realtime_leader_guide = 1
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    statusline_unicode_symbols = true
    buffer_index_type = 0
    todo_labels = ['@bug', '@question', '@idea', '@fixme']
    windows_index_type = 3
    statusline_separator = 'arrow'
    github_username = 'wsdjeg'
    auto_disable_touchpad = 0
    colorscheme = 'one'
    checkinstall = false
    guifont = 'SauceCodePro NF:h12:cANSI:qDRAFT'
    # guifont = 'SauceCodePro Nerd Font Mono:h12:cANSI:qDRAFT'
    # guifont = 'DejaVuSansMono NF:h12:cANSI:qDRAFT'
    # guifont = 'Hasklug NF:h12:cANSI:qDRAFT'
    enable_tabline_filetype_icon = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    search_tools = ["rg", "pt", "ack", "grep", "findstr"]
    # autocomplete_method = "coc"
    commandline_prompt = '>'
    # vimcompatible = true
    # enable_language_specific_leader = false
    enable_statusline_tag = false
# }}}

# SpaceVim layer config {{{
[[layers]]
    name = 'core'
    # filetree_show_hidden = true
[[layers]]
  name = "lang#python"
[[layers]]
    name = 'denite'
[[layers]]
    name = 'format'
[[layers]]
    name = 'git'
[[layers]]
    name = 'tools'
[[layers]]
    name = 'gtags'
    gtagslabel = 'pygments'
[[layers]]
    name = 'cscope'
[[layers]]
    name = 'VersionControl'
[[layers]]
    name = 'lang#vim'
[[layers]]
    name = 'lang#c'
[[layers]]
    name = 'lang#typescript'
[[layers]]
    name = 'lang#lua'
[[layers]]
    name = 'lang#sh'
    bash-file-head = [
        '#!/usr/bin/env bash',
        '# Time: `strftime("%Y-%m-%d %T")`',
        ''
    ]
[[layers]]
  name = "lsp"
  filetypes = [
    "typescript"
  ]
  [layers.override_cmd]
    rust = ["rustup", "run", "nightly", "rls"]
[[layers]]
    name = 'lang#haskell'
[[layers]]
    name = 'lang#javascript'
[[layers]]
    name = 'lang#xml'
[[layers]]
    name = 'lang#scheme'
    scheme_dialect = 'chez'
    scheme_interpreter = 'C:\Program Files\Chez Scheme 9.5\bin\ta6nt\scheme.exe'
[[layers]]
    name = 'debug'
[[layers]]
    name = 'lang#toml'
[[layers]]
    name = 'lang#ring'
    ring_repl = 'C:\Users\wsdjeg\SpaceVim\ringrepl\repl.ring'
[[layers]]
    name = 'colorscheme'
[[layers]]
    name = 'core#statusline'
    enable = true
[[layers]]
    name = 'core#tabline'
    enable = true
[[layers]]
    name = 'autocomplete'
    auto-completion-delay = 10
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = 'lang#markdown'
    enableWcwidth = 1
    listItemIndent = 1
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30
[[layers]]
    name = 'incsearch'
    enable = true
[[layers]]
    name = 'lang#xquery'
    enable = true
[[layers]]
    name = 'lang#janet'
    enable = true
[[layers]]
    name = 'lang#zig'
    enable = true
[[layers]]
    name = 'lang#vbnet'
    enable = true

[[custom_plugins]]
    name = 'jreybert/vimagit'
    merged = false

[[custom_plugins]]
    name = 'liuchengxu/vista.vim'
    merged = false
